FIELD_CATEGORIES = "displayCategories"
FIELD_TYPE = "type"
FIELD_COUNT = "count"
FIELD_ITEMDESC = "itemDesc"
FIELD_LOOTNAME = "lootName"
FIELD_DISENCHANT = "disenchantValue"
FIELD_PARENTID = "parentStoreItemId"

CATEGORY_CHEST = "CHEST"
CATEGORY_ETERNALS = "ETERNALS"
CATEGORY_SKINS = "SKIN"
CATEGORY_CHAMPION = "CHAMPION"

TYPE_MASTERY_TOKEN = "CHAMPION_TOKEN"
TYPE_CURRENCY = "CURRENCY"

TOKEN_NAME_MASTERY_SIX = "CHAMPION_TOKEN_7"
TOKEN_NAME_MASTERY_SEVEN = "CHAMPION_TOKEN_7"

CURRENCY_BLUE_ESSENCE = "CURRENCY_champion"
CURRENCY_ORANGE_ESSENCE = "CURRENCY_cosmetic"
CURRENCY_MYTHIC_ESSENCE = "CURRENCY_mythic"
CURRENCY_RP = "CURRENCY_RP"
